## Introduction to Numpy

#### **Name: Cesar Alonso Lopez Anguiano** <Insert name>


#### Import numpy

In [1]:
import numpy as np

#### Numpy operations
1.- Create array a with values from 1-5 \
2.- create an array b with values from 6 - 10

In [5]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [6]:
b = np.arange(6, 11)
b


array([ 6,  7,  8,  9, 10])

#### Matrix Operations with numpy

1. Create a 3x3 matrix in numpy with the following values: 

⎡ 1  2  3 ⎤ \
⎢ 4  5  6 ⎥ \
⎣ 7  8  9 ⎦ 

2.- Transpose the matrix and save it into a transpose variable \
3.- Add both matrix \
4.- Multiply both matrix



In [8]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
transpose = matrix.T
transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [10]:
sum_matrix = matrix + transpose
sum_matrix


array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [11]:
product_matrix = np.dot(matrix, transpose)
product_matrix


array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

#### numpy indexing

1.- Create a numpy array [10, 20, 30, 40, 50, 60] \
2.- print second and last index \
3.- print elements 1-3 \
4.- print all but the first 2 elements \
5.- reshape the array to be a 2x3 matrix 

In [13]:
arr = np.array([10, 20, 30, 40, 50, 60])
arr

array([10, 20, 30, 40, 50, 60])

In [17]:
arr[1]


np.int64(20)

In [18]:
arr[-1]

np.int64(60)

In [19]:
arr[1:4]

array([20, 30, 40])

In [20]:
arr[2:]

array([30, 40, 50, 60])

In [22]:
reshaped_arr = arr.reshape((2, 3))
reshaped_arr

array([[10, 20, 30],
       [40, 50, 60]])

#### Creating random arrays
1- Create a 3x3 matrix with random numbers. \
2.- Create a 2x3 matrix with random integers.


In [23]:
np.random.seed(42)
random_array = np.random.rand(3,3)
random_array


array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501]])

In [25]:
random_array_int = np.random.randint(0,10, size=(2,3))
random_array_int

array([[0, 9, 5],
       [8, 0, 9]], dtype=int32)

#### Boolean Indexing and Filtering
1.- Generate a random dataset in a 5x5 matrixs filled with integers from 1-50. \
2.- Filter the values that are bigger than 25 and replace them with 0. \
3.- Calculate the basic statisticañ dispersion and tendency meassurements.

In [26]:
dataset = np.random.randint(1,51, size=[5,5])
dataset

array([[28, 16, 15, 47, 44],
       [ 3, 37,  7, 21,  9],
       [39, 18,  4, 25, 14],
       [50,  9, 26,  2, 20],
       [28, 47,  7, 44,  8]], dtype=int32)

In [27]:
dataset[dataset > 25] = 0
dataset

array([[ 0, 16, 15,  0,  0],
       [ 3,  0,  7, 21,  9],
       [ 0, 18,  4, 25, 14],
       [ 0,  9,  0,  2, 20],
       [ 0,  0,  7,  0,  8]], dtype=int32)

In [30]:
np.mean(dataset)

np.float64(7.12)

In [31]:
np.median(dataset)

np.float64(4.0)

In [32]:
np.std(dataset)

np.float64(7.880710627855841)

In [33]:
np.var(dataset)

np.float64(62.105599999999995)

#### Homework exercise numpy

⎡ 2  3 ⎤ \
⎣ 0  1 ⎦ 


⎡ 1  2 ⎤  
⎣ 4  0 ⎦ 

1. The product
2. Product's transpose.
3. Determinant of the product
4. The inverse of the product.

In [35]:
A = np.array([[2, 3],[0, 1]])
B = np.array([[1, 2],[4, 0]])

In [39]:
C = np.dot(A, B)
C

array([[14,  4],
       [ 4,  0]])

In [40]:
transpose = C.T
transpose

array([[14,  4],
       [ 4,  0]])

In [41]:
determinante = np.linalg.det(C)
determinante

np.float64(-15.999999999999998)

In [42]:
inverse = np.linalg.inv(C)
inverse

array([[ 0.   ,  0.25 ],
       [ 0.25 , -0.875]])